/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'

const BecomeAGuideLazyRouteImport = createFileRoute('/become-a-guide')()
const AllpackagesLazyRouteImport = createFileRoute('/allpackages')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const GuideDashboardLazyRouteImport = createFileRoute('/guide/dashboard')()
const DashboardProfileLazyRouteImport = createFileRoute('/dashboard/profile')()
const AllpackagesIdLazyRouteImport = createFileRoute('/allpackages/$id')()
const GuideTourPlansCreateLazyRouteImport = createFileRoute(
  '/guide/tour-plans/create',
)()
const GuideTourPlansIdLazyRouteImport = createFileRoute(
  '/guide/tour-plans/$id',
)()
const GuideTourPlansIdIndexLazyRouteImport = createFileRoute(
  '/guide/tour-plans/$id/',
)()
const GuideTourPlansIdEditLazyRouteImport = createFileRoute(
  '/guide/tour-plans/$id/edit',
)()

const BecomeAGuideLazyRoute = BecomeAGuideLazyRouteImport.update({
  id: '/become-a-guide',
  path: '/become-a-guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/become-a-guide.lazy').then((d) => d.Route),
)
const AllpackagesLazyRoute = AllpackagesLazyRouteImport.update({
  id: '/allpackages',
  path: '/allpackages',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/allpackages.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GuideDashboardLazyRoute = GuideDashboardLazyRouteImport.update({
  id: '/guide/dashboard',
  path: '/guide/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guide/dashboard.lazy').then((d) => d.Route),
)
const DashboardProfileLazyRoute = DashboardProfileLazyRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dashboard.profile.lazy').then((d) => d.Route),
)
const AllpackagesIdLazyRoute = AllpackagesIdLazyRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AllpackagesLazyRoute,
} as any).lazy(() =>
  import('./routes/allpackages/$id.lazy').then((d) => d.Route),
)
const GuideTourPlansCreateLazyRoute =
  GuideTourPlansCreateLazyRouteImport.update({
    id: '/guide/tour-plans/create',
    path: '/guide/tour-plans/create',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/guide/tour-plans/create.lazy').then((d) => d.Route),
  )
const GuideTourPlansIdLazyRoute = GuideTourPlansIdLazyRouteImport.update({
  id: '/guide/tour-plans/$id',
  path: '/guide/tour-plans/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/guide/tour-plans/$id.lazy').then((d) => d.Route),
)
const GuideTourPlansIdIndexLazyRoute =
  GuideTourPlansIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GuideTourPlansIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/guide/tour-plans/$id/index.lazy').then((d) => d.Route),
  )
const GuideTourPlansIdEditLazyRoute =
  GuideTourPlansIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => GuideTourPlansIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/guide/tour-plans/$id/edit.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/allpackages': typeof AllpackagesLazyRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/allpackages/$id': typeof AllpackagesIdLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
  '/guide/dashboard': typeof GuideDashboardLazyRoute
  '/guide/tour-plans/$id': typeof GuideTourPlansIdLazyRouteWithChildren
  '/guide/tour-plans/create': typeof GuideTourPlansCreateLazyRoute
  '/guide/tour-plans/$id/edit': typeof GuideTourPlansIdEditLazyRoute
  '/guide/tour-plans/$id/': typeof GuideTourPlansIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/allpackages': typeof AllpackagesLazyRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/allpackages/$id': typeof AllpackagesIdLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
  '/guide/dashboard': typeof GuideDashboardLazyRoute
  '/guide/tour-plans/create': typeof GuideTourPlansCreateLazyRoute
  '/guide/tour-plans/$id/edit': typeof GuideTourPlansIdEditLazyRoute
  '/guide/tour-plans/$id': typeof GuideTourPlansIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/about': typeof AboutLazyRoute
  '/allpackages': typeof AllpackagesLazyRouteWithChildren
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/allpackages/$id': typeof AllpackagesIdLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
  '/guide/dashboard': typeof GuideDashboardLazyRoute
  '/guide/tour-plans/$id': typeof GuideTourPlansIdLazyRouteWithChildren
  '/guide/tour-plans/create': typeof GuideTourPlansCreateLazyRoute
  '/guide/tour-plans/$id/edit': typeof GuideTourPlansIdEditLazyRoute
  '/guide/tour-plans/$id/': typeof GuideTourPlansIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/about'
    | '/allpackages'
    | '/become-a-guide'
    | '/allpackages/$id'
    | '/dashboard/profile'
    | '/guide/dashboard'
    | '/guide/tour-plans/$id'
    | '/guide/tour-plans/create'
    | '/guide/tour-plans/$id/edit'
    | '/guide/tour-plans/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/about'
    | '/allpackages'
    | '/become-a-guide'
    | '/allpackages/$id'
    | '/dashboard/profile'
    | '/guide/dashboard'
    | '/guide/tour-plans/create'
    | '/guide/tour-plans/$id/edit'
    | '/guide/tour-plans/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/about'
    | '/allpackages'
    | '/become-a-guide'
    | '/allpackages/$id'
    | '/dashboard/profile'
    | '/guide/dashboard'
    | '/guide/tour-plans/$id'
    | '/guide/tour-plans/create'
    | '/guide/tour-plans/$id/edit'
    | '/guide/tour-plans/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SearchRoute: typeof SearchRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AllpackagesLazyRoute: typeof AllpackagesLazyRouteWithChildren
  BecomeAGuideLazyRoute: typeof BecomeAGuideLazyRoute
  DashboardProfileLazyRoute: typeof DashboardProfileLazyRoute
  GuideDashboardLazyRoute: typeof GuideDashboardLazyRoute
  GuideTourPlansIdLazyRoute: typeof GuideTourPlansIdLazyRouteWithChildren
  GuideTourPlansCreateLazyRoute: typeof GuideTourPlansCreateLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/become-a-guide': {
      id: '/become-a-guide'
      path: '/become-a-guide'
      fullPath: '/become-a-guide'
      preLoaderRoute: typeof BecomeAGuideLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allpackages': {
      id: '/allpackages'
      path: '/allpackages'
      fullPath: '/allpackages'
      preLoaderRoute: typeof AllpackagesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/dashboard': {
      id: '/guide/dashboard'
      path: '/guide/dashboard'
      fullPath: '/guide/dashboard'
      preLoaderRoute: typeof GuideDashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allpackages/$id': {
      id: '/allpackages/$id'
      path: '/$id'
      fullPath: '/allpackages/$id'
      preLoaderRoute: typeof AllpackagesIdLazyRouteImport
      parentRoute: typeof AllpackagesLazyRoute
    }
    '/guide/tour-plans/create': {
      id: '/guide/tour-plans/create'
      path: '/guide/tour-plans/create'
      fullPath: '/guide/tour-plans/create'
      preLoaderRoute: typeof GuideTourPlansCreateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/tour-plans/$id': {
      id: '/guide/tour-plans/$id'
      path: '/guide/tour-plans/$id'
      fullPath: '/guide/tour-plans/$id'
      preLoaderRoute: typeof GuideTourPlansIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/tour-plans/$id/': {
      id: '/guide/tour-plans/$id/'
      path: '/'
      fullPath: '/guide/tour-plans/$id/'
      preLoaderRoute: typeof GuideTourPlansIdIndexLazyRouteImport
      parentRoute: typeof GuideTourPlansIdLazyRoute
    }
    '/guide/tour-plans/$id/edit': {
      id: '/guide/tour-plans/$id/edit'
      path: '/edit'
      fullPath: '/guide/tour-plans/$id/edit'
      preLoaderRoute: typeof GuideTourPlansIdEditLazyRouteImport
      parentRoute: typeof GuideTourPlansIdLazyRoute
    }
  }
}

interface AllpackagesLazyRouteChildren {
  AllpackagesIdLazyRoute: typeof AllpackagesIdLazyRoute
}

const AllpackagesLazyRouteChildren: AllpackagesLazyRouteChildren = {
  AllpackagesIdLazyRoute: AllpackagesIdLazyRoute,
}

const AllpackagesLazyRouteWithChildren = AllpackagesLazyRoute._addFileChildren(
  AllpackagesLazyRouteChildren,
)

interface GuideTourPlansIdLazyRouteChildren {
  GuideTourPlansIdEditLazyRoute: typeof GuideTourPlansIdEditLazyRoute
  GuideTourPlansIdIndexLazyRoute: typeof GuideTourPlansIdIndexLazyRoute
}

const GuideTourPlansIdLazyRouteChildren: GuideTourPlansIdLazyRouteChildren = {
  GuideTourPlansIdEditLazyRoute: GuideTourPlansIdEditLazyRoute,
  GuideTourPlansIdIndexLazyRoute: GuideTourPlansIdIndexLazyRoute,
}

const GuideTourPlansIdLazyRouteWithChildren =
  GuideTourPlansIdLazyRoute._addFileChildren(GuideTourPlansIdLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SearchRoute: SearchRoute,
  AboutLazyRoute: AboutLazyRoute,
  AllpackagesLazyRoute: AllpackagesLazyRouteWithChildren,
  BecomeAGuideLazyRoute: BecomeAGuideLazyRoute,
  DashboardProfileLazyRoute: DashboardProfileLazyRoute,
  GuideDashboardLazyRoute: GuideDashboardLazyRoute,
  GuideTourPlansIdLazyRoute: GuideTourPlansIdLazyRouteWithChildren,
  GuideTourPlansCreateLazyRoute: GuideTourPlansCreateLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
