/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const GuidesLazyRouteImport = createFileRoute('/guides')()
const BecomeAGuideLazyRouteImport = createFileRoute('/become-a-guide')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const DashboardProfileLazyRouteImport = createFileRoute('/dashboard/profile')()

const GuidesLazyRoute = GuidesLazyRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/guides.lazy').then((d) => d.Route))
const BecomeAGuideLazyRoute = BecomeAGuideLazyRouteImport.update({
  id: '/become-a-guide',
  path: '/become-a-guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/become-a-guide.lazy').then((d) => d.Route),
)
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardProfileLazyRoute = DashboardProfileLazyRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dashboard.profile.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/guides': typeof GuidesLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/guides': typeof GuidesLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/become-a-guide': typeof BecomeAGuideLazyRoute
  '/guides': typeof GuidesLazyRoute
  '/dashboard/profile': typeof DashboardProfileLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-guide'
    | '/guides'
    | '/dashboard/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/become-a-guide' | '/guides' | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-guide'
    | '/guides'
    | '/dashboard/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  BecomeAGuideLazyRoute: typeof BecomeAGuideLazyRoute
  GuidesLazyRoute: typeof GuidesLazyRoute
  DashboardProfileLazyRoute: typeof DashboardProfileLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-guide': {
      id: '/become-a-guide'
      path: '/become-a-guide'
      fullPath: '/become-a-guide'
      preLoaderRoute: typeof BecomeAGuideLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  BecomeAGuideLazyRoute: BecomeAGuideLazyRoute,
  GuidesLazyRoute: GuidesLazyRoute,
  DashboardProfileLazyRoute: DashboardProfileLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
